### ISSUE TITLE
Add data/code link or equivalent field

### ISSUE THREAD

**Issue by amorim-cjs** [amorim-cjs/scigen-report#3]
We want to allow users to attach a Zenodo link or equivalent to data or code used in reproduction/replication. It should be a relatively simple task achievable by updating the submission forms under `source/src/scigen/views/reviews/` and the model `source/src/scigen/views/models/review_models.php`

**Comment by Visovsiouk** [comment]
Hello, can I take this task?

**Comment by amorim-cjs** [comment]
Yes, absolutely! It should be a quite straightforward update to do. 

I created a new branch called `hacktoberfest` to avoid having to deal directly with the master branch.

Thanks in advance!

**Comment by amorim-cjs** [comment]
@Visovsiouk , not sure if you are taking part on hacktoberfest, but there is still time to make a pull request this month and qualify for the challenge. Do you think you can make it?

**Comment by Visovsiouk** [comment]
@amorim-cjs I've added the needed code. Sorry for the late response. Please review when possible.

**Comment by amorim-cjs** [comment]
Thank you! It will be live with the UI renewal.
